version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
  pre_build:
    commands:
      - npm install -g serverless
  build:
    commands:
      - npm install
      - serverless deploy --stage dev # Replace 'dev' with your desired stage

artifacts:
  files:
    - serverless.yml